version: '3'
services:
  frontend:
    build: frontend
    ports:
      - "${FRONTEND_HOST_PORT:-8000}:${FRONTEND_CONTAINER_PORT:-8000}"
    environment:
      - ENDPOINT=${BACKEND_PROTOCOL:-http}://${BACKEND_HOSTNAME:-localhost}:${BACKEND_CONTAINER_PORT:-9000}${BACKEND_PATH:-/api}
    command: npm run ${FRONTEND_SCRIPT:-start}
  backend:
    build: backend
    environment:
      - APPID=${APPID:?APPID must be set and not empty}
    ports:
      - "${BACKEND_HOSRT_PORT-9000}:${BACKEND_CONTAINER_PORT-9000}"
    command: npm run ${BACKEND_SCRIPT:-start}
