---
- hosts: weatherapp
  become: True
  vars:
    docker_prerequisites:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    weatherapp_project_dir: /opt/weatherapp
  tasks:
  - name: Install prerequisites for installing docker
    apt:
      name: "{{ docker_prerequisites }}"
      state: present
      update_cache: no
  - name: Add apt key for docker repository
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Get release codename
    command: lsb_release -cs
    register: release_codename
  - name: Add apt repository for docker
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release_codename.stdout }} stable
      state: present
  - name: Install docker
    apt:
      name: docker-ce
      state: present
  - name: Ensure docker service is running
    service:
      name: docker
      enabled: yes
      state: started
  - name: Intall pip
    apt:
      name: python3-pip
      state: present
  - name: Install docker-compose
    pip:
      name: docker-compose
      state: present
  - name: Install git
    apt:
      name: git
      state: present
  - name: Get app
    git:
      repo: "https://github.com/hirvinen/weatherapp"
      dest: "{{ weatherapp_project_dir }}"
  - name: Copy .env
    copy:
      src: "{{ WEATHERAPP_ENV_FILE }}"
      dest: "{{ weatherapp_project_dir }}/.env"
  - name: Run the app
    docker_service:
      build: yes
      project_src: "{{ weatherapp_project_dir }}"
      files:
      - docker-compose.yml
      - docker-compose.nginx-proxy.yml
      state: present
